config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :sub_orders
  resources :customer_orders
  resources :cashouts

  root 'pages#index'
  
  get '/order_new' => 'sub_orders#index'
  get '/admin' => 'pages#admin'
  get '/admin/orders' => 'customer_orders#admin'
  get '/admin/all_sub_orders' => 'sub_orders#admin'

end

app/models/cashout.rb
class Cashout < ActiveRecord::Base
	belongs_to :customer_order
end

app/models/customer_order.rb
class CustomerOrder < ActiveRecord::Base
	has_many :sub_orders
	has_one :cashout

	validates :customer_name, :presence => true
	validates :contact_number, :presence => true
	validates :email, :presence => true
	validates :address, :presence => true
end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :sub_order

	validates :name, :presence => true
	validates :foodtype, :presence => true
	validates :price, :presence => true
end

app/models/sub_order.rb
class SubOrder < ActiveRecord::Base
	has_many :foods
	belongs_to :customer_order
end

app/models/suborder.rb
class Suborder < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cashouts_controller.rb
class CashoutsController < ApplicationController
	def index
		
	end

	def new
		@cashout = Cashout.new 
	end

	def create
		@cashout = Cashout.new
		@cashout.customer_order_id = params[:cashout][:customer_id]
		@cashout.total_sale_price = params[:cashout][:c_sub_total]
		@cashout.delivery_charge = params[:cashout][:c_del_charge]
		@cashout.grand_total_sale_price = params[:cashout][:c_grand_total]
		@cashout.save!
		redirect_to :action => :index
	end

	def thanks
		
	end
end

app/controllers/customer_orders_controller.rb
class CustomerOrdersController < ApplicationController
	attr_accessor :id, :c_id

	def index
		@customer_orders = CustomerOrder.all
	end

	def new
		@customer_order = CustomerOrder.new
	end

	def create
		@customer_order = CustomerOrder.new
		@customer_order.customer_name = params[:customer_order][:customer_name]
		@customer_order.contact_number = params[:customer_order][:contact_number]
		@customer_order.email = params[:customer_order][:email]
		@customer_order.address = params[:customer_order][:address]
		@customer_order.order_date = params[:customer_order][:order_date]
		
		if @customer_order.save
		id = @customer_order.id
		redirect_to(sub_orders_path(:c_id => id))

		else
			render :new
		end
	end

	def edit
		@customer_order = CustomerOrder.find(params[:id])
	end

	def update
		@customer_order = CustomerOrder.find(params[:id])
		@customer_order.customer_name = params[:customer_order][:customer_name]
		@customer_order.contact_number = params[:customer_order][:contact_number]
		@customer_order.email = params[:customer_order][:email]
		@customer_order.address = params[:customer_order][:address]
		@customer_order.order_date = params[:customer_order][:order_date]
		
		if @customer_order.save
		id = @customer_order.id
		redirect_to :action => :admin

		else
			render :edit
		end
	end

	def destroy
		@customer_order = CustomerOrder.find(params[:id])
		@customer_order.destroy!
		redirect_to :action => :admin
	end

	def admin
		@customer_orders = CustomerOrder.all
	end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def index
		@foods = Food.all
	end

	def show
		@food = Food.find(params[:id])
	end

	def new
		@food = Food.new
	end

	def create
		@food = Food.new
		@food.name = params[:food][:name]
		@food.foodtype = params[:food][:foodtype]
		@food.price = params[:food][:price]

		if @food.save
			redirect_to :action => :index
		else
			render :new
		end
	end

	def edit
		@food = Food.find(params[:id])
	end

	def update
		@food = Food.find(params[:id])
		@food.name = params[:food][:name]
		@food.foodtype = params[:food][:foodtype]
		@food.price = params[:food][:price]

		if @food.save
			redirect_to :action => :index
		else
			render :edit
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def admin
		render 'admin'
	end
end

app/controllers/sub_orders_controller.rb
class SubOrdersController < ApplicationController
	attr_accessor :food, :sub_order, :food_id, :id, :c_id
	def index
		@foods = Food.all
		#@sub_orders = SubOrder.find_by(:customer_order_id, :c_id)
		@sub_orders = SubOrder.where(:customer_order_id => params[:c_id])
		@delivery_charge = 40
	end

	def new
		#@food = Food.find(params[:id])
		#@food = Food.all
		@food = Food.find(params[:id])
		@sub_order = SubOrder.new
	end

	def create
		@sub_order = SubOrder.new
		@sub_order.customer_order_id = params[:sub_order][:cust_id]
		id = @sub_order.customer_order_id
		@sub_order.food_id = params[:sub_order][:food_id]
		@sub_order.name = params[:sub_order][:name]
		@sub_order.foodtype = params[:sub_order][:foodtype]
		@sub_order.quantity = params[:sub_order][:quantity]
		@price = params[:sub_order][:price]
		total = @price.to_i * @sub_order.quantity.to_i

		@sub_order.totalprice = total
		#@suborder.save!
		#@sub_order.foods << Food.find(params[:id])
		@sub_order.save!

		redirect_to(sub_orders_path(:c_id => id))
	end

	def edit
		@sub_order = SubOrder.find(params[:id])
		@food = Food.find(@sub_order.food_id)
	end

	def update
		@sub_order = SubOrder.find(params[:id])
		@sub_order.customer_order_id = params[:sub_order][:cust_id]
		id = @sub_order.customer_order_id
		@sub_order.food_id = params[:sub_order][:food_id]
		@sub_order.name = params[:sub_order][:name]
		@sub_order.foodtype = params[:sub_order][:foodtype]
		@sub_order.quantity = params[:sub_order][:quantity]
		@price = params[:sub_order][:price]
		total = @price.to_i * @sub_order.quantity.to_i

		@sub_order.totalprice = total
		#@suborder.save!
		#@sub_order.foods << Food.find(params[:id])
		@sub_order.save!

		redirect_to(sub_orders_path(:c_id => id))
	end

	def destroy
		@sub_order = SubOrder.find(params[:id])
		@sub_order.destroy!
		redirect_to :action => :index	
	end

	def admin
		@sub_orders = SubOrder.where(:customer_order_id => params[:c_id])
		@cashouts = Cashout.where(:customer_order_id => params[:c_id])
		@delivery_charge = 40
	end
end

app/controllers/suborders_controller.rb
class SubordersController < ApplicationController
	attr_accessor :food, :sub_order

	def index
		@foods = Food.all
		@suborders = Suborder.all
	end

	def new
		#@food = Food.find(params[:id])
		#@food = Food.all
		@food = Food.find(params[:id])
		@suborder = Suborder.new
	end

	def create
		@suborder = Suborder.new
		@suborder.name = params[:suborder][:name]
		@suborder.foodtype = params[:suborder][:foodtype]
		@suborder.quantity = params[:suborder][:quantity]
		@price = params[:suborder][:price]
		#total = @food.price * @suborder.quantity

		@suborder.totalprice = params[:suborder][total]
		#@suborder.save!
		#@sub_order.foods << Food.find(params[:id])
		@suborder.save!

		redirect_to :action => :index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashouts_helper.rb
module CashoutsHelper
end

app/helpers/customer_orders_helper.rb
module CustomerOrdersHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sub_orders_helper.rb
module SubOrdersHelper
end

app/helpers/suborders_helper.rb
module SubordersHelper
end

app/views/cashouts/index.html.erb
<center>
<ty>Thank You!</ty>
<br>
<ty2>Your ordered has now been processed. <br>Just wait for it to arrive at your place.</ty2>

<br><br><%= link_to "Back to Home", "/", :class => "button-style" %>
</center>

app/views/cashouts/new.html.erb
<div id="box4-alt">
<center>
<h2>Delivery Total<br>
<span>LAST STEP</span>
</h2>
<p>Dear Customer! Here's the cashout summary for your order.</p>
<br>
<%= form_for @cashout do |f| %>
<% f.hidden_field :customer_id, :value => params[:c_id] %>
	<table id="cashout_table">
		<tr>
			<td class="cashout_label">Total: </td>
			<td>Php <%= f.text_field :c_sub_total, :value => params[:sub_total], :readonly => true %></td>
		</tr>
		<tr>
			<td class="cashout_label">Delivery Charge: </td>
			<td>Php <%= f.text_field :c_del_charge, :value => params[:del_charge], :readonly => true  %></td>
		</tr>
		<tr>
			<td class="cashout_label">Grand Total: </td>
			<td>Php <%= f.text_field :c_grand_total, :value => params[:grand_total], :readonly => true  %></td>
		</tr>
	</table>
	<br>
	<%= f.submit "PROCEED", :class => "button-style" %>
<% end %>
</center>
</div>

app/views/customer_orders/_form.html.erb
<%= form_for customer_order do |f| %>
<table class="table_form">
	<tr>
		<td>Customer Name: </td>
		<td><%= f.text_field :customer_name %></td>
	</tr>

	<tr>
		<td>Contact Number: </td>
		<td><%= f.text_field :contact_number %></td>
	</tr>

	<tr>
		<td>Email: </td>
		<td><%= f.text_field :email %></td>
	</tr>

	<tr>
		<td>Address: </td>
		<td><%= f.text_field :address %></td>
	</tr>

	<tr>
		<td>Order Date: </td>
		<td><%= f.date_field :order_date, :value => Time.now.strftime("%Y-%m-%d"), :readonly => true %></td>
	</tr>
</table>
<center><%= f.submit "Enter", :class => "button-style"%></center>
<% end %>

app/views/customer_orders/admin.html.erb
<center>
<h2>All Orders
<br><span>SEE ALL THE ORDERS ON THE GO</span></h2>

<p>Here you can see all the orders that were received!</p>

	<table id="admin_table">
		<tr>
			<th>Order ID</th>
			<th>Customer Name</th>
			<th>Contact Number</th>
			<th>Email</th>
			<th>Address</th>
			<th>Order Date</th>
			<th>See Orders</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
<% @customer_orders.each do |customer_order| %>
		<tr>
			<td><%= customer_order.id %></td>
			<td><%= customer_order.customer_name %></td>
			<td><%= customer_order.contact_number %></td>
			<td><%= customer_order.email %></td>
			<td><%= customer_order.address %></td>
			<td><%= customer_order.order_date %></td>
			<td><%= link_to "SEE ALL ORDERS", admin_all_sub_orders_path(:c_id => customer_order.id), :class => "button-style-4" %></td>
			<td><%= link_to "EDIT", edit_customer_order_path(customer_order.id), :class => "button-style" %></td>
			<td><%= link_to "DELETE", customer_order, :method => :delete, :class => "button-style-2" %></td>
		</tr>
<% end %>
</table>

<%= link_to "Back to Admin Home Page", "/admin", :class => "button-style"%>
</center>

app/views/customer_orders/edit.html.erb
<div id="box4">
<h2>EDIT CUSTOMER ORDER
<br><span>ORDER CHANGER</span></h2>
<% if @customer_order.errors.any? %>
<div class="error">
	ERROR:<br>
	<ul>
	<% @customer_order.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
</div>
<% end %>

<p>You may now do changes to this customer order, Admin!</p>

<%= form_for @customer_order do |f| %>
<table class="table_form">
	<tr>
		<td>Customer Name: </td>
		<td><%= f.text_field :customer_name %></td>
	</tr>

	<tr>
		<td>Contact Number: </td>
		<td><%= f.text_field :contact_number %></td>
	</tr>

	<tr>
		<td>Email: </td>
		<td><%= f.text_field :email %></td>
	</tr>

	<tr>
		<td>Address: </td>
		<td><%= f.text_field :address %></td>
	</tr>

	<tr>
		<td>Order Date: </td>
		<td><%= f.date_field :order_date, :readonly => true %></td>
	</tr>
</table>
<center><%= f.submit "Enter", :class => "button-style"%></center>
<% end %>

</div>

app/views/customer_orders/index.html.erb
<center>
<div id="box4">
	<h2>DELIVERY
	<br><span>Enter Your Details First</span></h2>

	<p>Hello Dear Customer! I know you are excited to have your online delivery but first please enter your details. You can start by clicking the button below.</p>
<%= link_to "Enter", new_customer_order_path, :class => "button-style" %>
</div>
</center>

app/views/customer_orders/new.html.erb
<div id="box4">
<h2>Hello Customer!
<br><span>Enter your details here</span></h2>
<% if @customer_order.errors.any? %>
<div class="error">
	ERROR:<br>
	<ul>
	<% @customer_order.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
</div>
<% end %>

<p>So here's the contact form for your delivery. Please fill it out!</p>
 <%= render partial: "customer_orders/form", locals: { customer_order: @customer_order } %>
</div>

app/views/foods/_form.html.erb
<%= form_for food do |f| %>
	<table id="table_form">
    	<tr>
    		<td>Food Name: </td>
    		<td><%= f.text_field :name %></td>
    	</tr>

    	<tr>
    		<td>Food Type: </td>
    		<td><%= f.text_field :foodtype %></td>
    	</tr>    

    	<tr>
    		<td>Price</td>
    		<td><%= f.text_field :price %></td>
    	</tr>
    	
    	<tr>
    		<td><%= f.submit "Save", :class => "button-style" %></td>
    	</tr>
    </table>
 <% end %>

app/views/foods/edit.html.erb
<div id="box4">
<h2>EDIT THE FOOD
<br><span>Change the food entry here</span></h2>
<% if @food.errors.any? %>
<div class="error">
	ERROR:<br>
	<ul>
	<% @food.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
</div>
<% end %>
<p>In this form you can make changes in the food entry.</p>
	<%= render partial: "foods/form", locals: { food: @food } %>
</div>

app/views/foods/index.html.erb
<h2>Food Products
<br><span>ALL THE FOOD IN THE HOUSE</span></h2>
<p>Hello Admin! So, in this page you can enter new food products to be displayed in the restaurant. <br><i><b>Note:</b> Click on the food's name if you want to edit its attributes.</i></p>
<% @foods.each do |food| %>
	<p id="each_food">
		<b>Food ID:</b> <%= food.id %><br>
		<b>Food Name:</b> <name><%= link_to food.name, food_path(food.id) %></name><br />
		<b>Food Type:</b> <foodtype>[ <%= food.foodtype %> ]</foodtype><br />
		<b>Price:</b> Php <%= food.price.to_f %><br />
		<%= link_to 'Edit', edit_food_path(:id => food.id), :class => "button-style-5" %>
	</p>
<% end %> 
<br><br>
 <p><%= link_to 'Create New Food Entry', new_food_path, :id => "submit_btn" %></p>

<center>
 <%= link_to 'Back to Admin Page', "/admin", :class => "button-style-2" %>
</center>

app/views/foods/new.html.erb
<div id="box4">
<h2>NEW FOOD
<br><span>ADD A NEW FOOD ENTRY HERE</span></h2>
<% if @food.errors.any? %>
<div class="error">
	ERROR:<br>
	<ul>
	<% @food.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
</div>
<% end %>
 <%= render partial: "foods/form", locals: { food: @food } %>
</div>

app/views/foods/show.html.erb
<h1><%= @food.name %></h1>
<p>Type:	<%= @food.foodtype %></p>
<p>Price: 	<%= @food.price %></p>
<%= link_to 'Go back to Foods List', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avant Garde Eatery</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700|Raleway:400,700,200,300,900,800" rel="stylesheet" type="text/css">

  	<%= stylesheet_link_tag 'stylesheets/default' %>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper" class="container">
	<div id="header">
		<div id="logo">
			<h1><a href="#"><span>Avante Garde</span>Eatery</h1>			
			<p>NEOPHYTE IN ONLINE DELIVERY. BUT NOT IN FOOD QUALITY.</p>
		</div>
		<div id="menu">
			<ul>
				<li class="first current_page_item"><%= link_to 'Homepage', '/' %></li>
				<li><%= link_to 'Order Now', customer_orders_path %></a></li>
				<li><%= link_to 'About Us', '#' %></a></li>
			</ul>
		</div>
	</div>

<div id="page">
	<div class="content">
		<div id="cbox">
		<span>Avant Garde Eatery</span>
		<h2>NOW WITH ONLINE DELIVERY</h2>
		<p>Experience our new online delivery system! It's amazing.</p>
		<center>
		<%= link_to 'Order Now', customer_orders_path, :class => "button-style button-style-alt" %>
		</center>
		</div>
	</div>
</div>
<div id="featured-wrapper">
	<%= yield %>
</div>

	<div id="footer-content" class="container">
		<div id="fbox1">
			<h2>Recent Updates</h2>
			<ul class="style1">
				<li class="first"><a href="#">New Avant Garde branch in Riddle City</a></li>
				<li><a href="#">Best Diner in town is Avant Garde</a></li>
				<li><a href="#">'Avant Garde' is on the boom</a></li>
				<li><a href="#">New food products are available in Avant Garde</a></li>
			</ul>
		</div>
		<div id="fbox2">
			<h2>About</h2>
			<p>This is<strong> Avant Garde Eatery's Website</strong> a dummy restaurant website with an online delivery system for MIS21. This was made by Fritz Masiglat from scratch - except for the CSS Theme (originally from Templated.Co but was modified) and the images which were searched in Google. Also, some of the codes in the website were adapted from Stack Overflow. Feel free to explore the website.</p>
			<a href="#" class="button-style">See more of Avant Garde Eatery</a> </div>
		<div id="fbox3">
			<h2>Contact</h2>
			<p>You can keep in touch with Avant Garde Eatery online. Check the different social accounts below.</p>
			<ul class="style2">
				<li><a href="#"><img src="assets/social03.png" width="32" height="32" alt="" /></a></li>
				<li><a href="#"><img src="assets/social01.png" width="32" height="32" alt="" /></a></li>
				<li><a href="#"><img src="assets/social04.png" width="32" height="32" alt="" /></a></li>
				<li><a href="#"><img src="assets/social02.png" width="32" height="32" alt="" /></a></li>
			</ul>
		</div>
	</div>
<div id="footer">
	<p>© Copyright Avante Garde Eatery 2014 | Fritz Masiglat</p>
</div>

</body>
</html>

app/views/pages/admin.html.erb
<center>
<div id="box4">
	<h2>ADMIN PAGE
	<br><span>You're the boss around here</span></h2>

	<p>Hello Dear Admin! I know you are excited to explore your administrative skills but please have time to read these instructions so that you'll know how to manipulate this site. </p>

	<p>Here are the links with their respective functions</p>
	<table id="admin_table">
		<tr>
			<th>FUNCTION</th>
			<th>LINK</th>
		</tr>
		<tr>
			<td>To SEE all Food Products and ENTER new ones</td>
			<td><%= link_to "See Food Entries", foods_path, :class => "button-style-2" %></td>
		</tr>

		<tr>
			<td>To SEE all Online Orders</td>
			<td><%= link_to "See All Orders", '/admin/orders', :class => "button-style-2" %></td>
		</tr>
	</table>
</div>
</center>

app/views/pages/index.html.erb
<div id="box1">
<h2>AVANT GARDE EATERY
<br><span>THE FAMOUS EATERY IN TOWN</span></h2>
<ul class="style3"><li class="first"><p class="date"><a href="#">SINCE<b>2014</b></a></p></li><p id="desc">Avant Garde Eatery has been able to uphold it's virtue of excellence and quality as a legitimate diner, ever since it started. From the start of 2014, the restaurant has been successful in its own right.</p></ul>
<br><img src="assets/img_a.jpg"><br>
<%= link_to "Read more", "#", :class => "button-style-3" %>
</div>

<div id="box2">
<h2>AMBIENCE IS EXCELLENT
<br><span>Feel like you're going back in time</span></h2>
<center>
<img src="assets/inside_diner.jpg">
</center><br>
<p style="text-align: justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The restaurant is full of things that will make you feel happy and vibrant. It will make you reminisce the good ol' days. Surely, your stay here will be brilliant.</p>
</div>

<div id="box3">
<h2>FOOD IS EXQUISITE
<br><span>LOVE THE FOOD. BIG TIME.</span></h2>
<center><img src="assets/img_b.jpg"></center>
<br>
<p style="text-align: justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Of course, you should not forget about trying the food. The food of Avant Garde Eatery is definitely exquisite. The ingredients used for its food are of the best quality rendering the most brilliant taste. It's just delicious.</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;What are you waiting for? Go to the restaurant now or make an order online!</p>
<%= link_to "Order Now", customer_orders_path , :class => "button-style-3" %>
</div>

app/views/sub_orders/_form.html.erb
<%= form_for sub_order do |f| %>
<table class="table_form">
<%= f.text_field :cust_id, :value => params[:c_id], :hidden => true %>
<%= f.text_field :food_id, :value => @food.id, :hidden => true %>

	<tr>
		<td>Name:</td> 
		<td><%= f.text_field :name, :value => @food.name, :readonly => true %></td>
	</tr>

	<tr>
		<td>Type: </td>
		<td><%= f.text_field :foodtype, :value => @food.foodtype, :readonly => true %></td>
	</tr>

	<tr>
		<td>Price: </td>	
		<td><%= f.text_field :price, :value => @food.price, :readonly => true %></td>
	</tr>
	<tr>
		<td>Quantity: </td> 
		<td><%= f.number_field :quantity, :value => 1, :min => 1%></td>
	</tr>
</table>
<%= f.submit "Save", :class => "button-style"  %>
<% end %>
<%= link_to 'Go back to Foods List', sub_orders_path(params[:c_id]), :class => "button-style-2" %>

app/views/sub_orders/admin.html.erb
<center>
<h2>CUSTOMER ORDERS
<br><span>THIS THE FOOD BOX</span></h2>

<table id="admin_table">
	<tr>
		<th>Items</th>
		<th>Quantity</th>
		<th>Item Price</th>
		<th>Total Price</th>
	</tr>
<% @sub_orders.each do |sub_order| %>
	<tr>
		<td>
			<%= sub_order.name %><br />
			<%= sub_order.foodtype %><br />
		</td>
		<td><%= sub_order.quantity.to_f %></td>
		<td>Php <%= sub_order.totalprice.to_f / sub_order.quantity.to_f %></td>
		<td>Php <%= sub_order.totalprice.to_f %></td>
	</tr>
<% @sub_orders_total = @sub_orders_total.to_i + sub_order.totalprice %>
<% end %>
</table>
<br>
<p>
<b>Total:</b> Php <%= @sub_orders_total.to_f %><br />
<b>Delivery Charge:</b> Php <%= @delivery_charge.to_f %> <br />
<% @grand_total = @sub_orders_total.to_f + @delivery_charge.to_f %>
<b>Grand Total:</b> Php <%= @grand_total.to_f %>
</p>
<br><br>

<%= link_to "Back to Customer Orders", "/admin/orders", :class => "button-style"%>
</center>

app/views/sub_orders/edit.html.erb
<div id="box4">
<center>
<h2>ORDER<br>
<span>ENTER THE QUANTITY</span></h2>
<p>Simply enter the quantity in the corresponding field and press the button if you're done.</p>
<%= render partial: "sub_orders/form", locals: { sub_order: @sub_order } %>
</center>
</div>

app/views/sub_orders/index.html.erb
<center><h1>CHOOSE YOUR FOOD</h1></center><br>
<div id="box5">
<h1>Order Now</h1>
<br>
<% @foods.each do |food| %>
	<p id="each_food">
		<% food.id %>
		<name><%= food.name %></name><br />
		<foodtype>[ <%= food.foodtype %> ]</foodtype><br />
		Php <%= food.price.to_f %><br />
		<%= link_to "Add to Tray", new_sub_order_path(:id => food.id, :c_id => params[:c_id]), :id => "submit_btn" %>
	</p>
<% end %> 
</div>

<div id="box6">
<h2>Your Tray
<br><span>THIS IS YOUR FOOD BOX</span></h2>
<table id="order_table">
	<tr>
		<th>Items</th>
		<th>Quantity</th>
		<th>Item Price</th>
		<th>Total Price</th>
		<th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
	</tr>
<% @sub_orders.each do |sub_order| %>
	<tr>
		<td>
			<%= sub_order.name %><br />
			<%= sub_order.foodtype %><br />
		</td>
		<td><%= sub_order.quantity.to_f %></td>
		<td>Php <%= sub_order.totalprice.to_f / sub_order.quantity.to_f %></td>
		<td>Php <%= sub_order.totalprice.to_f %></td>
		<td><%= link_to "Edit", edit_sub_order_path(sub_order.id, :c_id => params[:c_id]), :class => "mini_btn" %> | 
		<%= link_to "Remove", sub_order, :method => :delete, :class => "mini_btn2" %></td>
	</tr>
<% @sub_orders_total = @sub_orders_total.to_i + sub_order.totalprice %>
<% end %>
</table>
<br>
<b>Total:</b> Php <%= @sub_orders_total.to_f %><br />
<b>Delivery Charge:</b> Php <%= @delivery_charge.to_f %> <br />
<% @grand_total = @sub_orders_total.to_f + @delivery_charge.to_f %>
<b>Grand Total:</b> Php <%= @grand_total.to_f %>
<br><br>
<hr>
<center>
<h1>Proceed to Cash Out</h1>
<%= link_to "Cash Out", new_cashout_path(:sub_total => @sub_orders_total.to_f, :del_charge => @delivery_charge.to_f, :grand_total => @grand_total.to_f, :c_id => params[:c_id]), :class => "button-style" %>
</center>
</div>

app/views/sub_orders/new.html.erb
<div id="box4">
<center>
<h2>ORDER<br>
<span>ENTER THE QUANTITY</span></h2>
<p>Simply enter the quantity in the corresponding field and press the button if you're done.</p>
<%= render partial: "sub_orders/form", locals: { sub_order: @sub_order } %>
</center>
</div>

app/views/suborders/index.html.erb
<h1>Order Now</h1>
<% @foods.each do |food| %>
	<p>
		<%= food.id %><br />
		<%= food.name %><br />
		<%= food.foodtype %><br />
		<%= food.price %><br />
		<%= link_to "Add to Tray", new_sub_order_path(:id => food.id) %>
<% end %>  

app/views/suborders/new.html.erb
<h1>Order </h1>
<%= render partial: "sub_orders/form", locals: { sub_order: @sub_order } %>